name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build app image
        run: |
          docker-compose build
          docker tag films-assembly_app:latest den255/film-assembly:latest
          docker login --help -u user -p password
          docker push den255/film-assembly:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy app
        run: |
          scp docker-compose.deploy.yml user@ip:/opt/film-assembly/
          ssh user@ip 'cd /opt/film-assembly/ && docker-compose -f docker-compose.deploy.yml up -d'
