name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build app image
        run: |
          docker-compose build
          docker tag films-assembly_app:latest den255/film-assembly:latest
          docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASSWORD}}
          docker push den255/film-assembly:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Copy compose file
        run: |
          echo ${{ secrets.KEY }} >> deploy.pub && chmod 600 deploy.pub
          cat deploy.pub
          scp -v -i deploy.pub -o StrictHostKeyChecking=no ./docker-compose.deploy.yml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/opt/film-assembly/docker-compose.deploy.yml
          ssh -v -i deploy.pub -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /opt && docker-compose -f docker-compose.deploy.yml up -d"
