name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build app image
        run: |
          docker-compose build
          docker tag films-assembly_app:latest den255/film-assembly:latest
          docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASSWORD}}
          docker push den255/film-assembly:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Copy compose file
        run: |
          mkdir ~/.ssh && echo ${{ secrets.KEY }} > ~/.ssh/id_rsa.pub
          scp ${{ secrets.USERNAME }}@${{ secrets.HOST }} ./docker-compose.deploy.yml:/opt/docker-compose.deploy.yml
          ssh  ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /opt && docker-compose -f docker-compose.deploy.yml up -d"
